# Generated by Django 5.2.9 on 2026-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_currency_job_description_job_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
