# Generated by Django 5.2.10 on 2026-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
