# Generated by Django 5.2.10 on 2026-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
